version: '3.9'

services:
  web:
    container_name: nest_container
    image: 389798/nest-image
    build: ./
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 4500:4500

  db:
    container_name: mongo_container
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_CLUSTER
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

networks:
  default:
