version: '3.9'

services:
  web:
    container_name: nest_container
    image: 389798/nest-image
    build: ./
    env_file:
      - .env
    restart: always
    volumes:
      - ./models:/app/models
    ports:
      - 4500:4500

  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nest-project
networks:
  default:
